import {createRequire} from 'node:module';import {mkdir,writeFile,readFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const ROOT=path.dirname(fileURLToPath(import.meta.url)),evidence=path.join(ROOT,'evidence'),reports=path.join(ROOT,'reports');await mkdir(reports,{recursive:true});await mkdir(path.join(evidence,'expressions'),{recursive:true});
const smoke=process.argv.includes('--smoke');const report={startedAt:new Date().toISOString(),success:false,smoke,loaded:[],consoleErrors:[],pageErrors:[],failedRequests:[],badResponses:[],checks:{},releaseConnected:false};
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const context=await browser.newContext({viewport:{width:1600,height:1100},deviceScaleFactor:1});const page=await context.newPage();page.setDefaultTimeout(90000);
page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('pageerror',e=>report.pageErrors.push(String(e)));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),failure:r.failure()}));page.on('response',r=>{if(r.status()>=400)report.badResponses.push({url:r.url(),status:r.status()});});
const check=(value,label)=>{if(!value)throw new Error(label);};const getState=()=>page.evaluate(()=>window.__v90.getState());const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const save=(name,value)=>writeFile(path.join(reports,name),JSON.stringify(value,null,2)+'\n');const capture=async filename=>{await settle();const data=await page.locator('#candidate').evaluate(c=>c.toDataURL());await writeFile(path.join(evidence,filename),Buffer.from(data.split(',')[1],'base64'));};
const hash=async()=>createHash('sha256').update(await page.locator('#candidate').evaluate(c=>c.toDataURL())).digest('hex');
try{
 console.log('Opening V90');await page.goto('http://127.0.0.1:43190/');await page.waitForFunction(()=>window.__v90?.getState()?.ready||window.__v90?.getState()?.error);const initial=await getState();check(initial.ready,initial.error);report.initial=initial;check(initial.expressionIds.length===34,'34 expressions required');
 const ids=smoke?['thinking','laugh','teary','love','sparkly','ee','shy','yawning']:initial.expressionIds;
 for(const id of ids){await page.locator('#expression').selectOption(id);await page.waitForFunction(id=>window.__v90.getState().expression===id&&!window.__v90.getState().busy,id);const current=await getState();check(current.material.inkPixels>0,'Empty expression '+id);check(current.asset.topologyVerified,'Topology not verified '+id);const row={id,label:current.asset.label,version:current.expressionVersion,sourceSHA256:current.asset.modelSHA256,material:current.material,captures:[]};
  for(const view of (smoke?['front']:['front','quarter','side'])){await page.locator(`[data-view="${view}"]`).click();const file=`expressions/${id}-${view}.png`;await capture(file);row.captures.push(file);}
  report.loaded.push(row);await save(smoke?'smoke-validation.json':'browser-validation.json',report);console.log(`${report.loaded.length}/${ids.length} ${id}: ${current.material.pigmentComponents.length} components, ${current.material.coloredPixels} color pixels`);
 }
 if(!smoke){
  await page.evaluate(()=>{window.__v90.reset();window.__v90.setMode('original');});await settle();const before=await hash();await page.locator('[data-mode="trial"]').click();await settle();const trial=await hash();await page.locator('[data-mode="original"]').click();await settle();const after=await hash();check(before===after&&before!==trial,'Original restoration failed');report.checks.originalRestoreExact=true;
  await page.evaluate(()=>{window.__v90.setView('back');window.__v90.setMode('trial');});await settle();const back=await hash();await page.locator('[data-mode="original"]').click();await settle();check(back===await hash(),'Back changed');report.checks.backUnchanged=true;
  const invariants=await page.evaluate(()=>window.__v90.invariants());check(invariants.baseBuffersSkinAndClipsUnchanged,'Base model data changed');await save('runtime-preservation.json',invariants);report.checks.baseBuffersSkinAndClipsUnchanged=true;
  report.actions=[];for(const [id,action]of [['thinking','HeadTilt'],['cheering','Cheer'],['greeting_smile','Wave'],['teary','Walk']]){await page.evaluate(async id=>{await window.__v90.selectExpression(id);window.__v90.reset();window.__v90.setFocus('body');window.__v90.setView('quarter');},id);await page.locator('#action').selectOption(action);for(const p of [0,35,70]){await page.evaluate(p=>window.__v90.seek(p),p);const file=`${id}-${action}-${p}.png`;await capture(file);report.actions.push(file);}}
  await page.evaluate(async()=>{await window.__v90.selectExpression('cheering');window.__v90.reset();window.__v90.setFocus('body');window.__v90.setView('quarter');});await page.locator('#action').selectOption('Cheer');const download=page.waitForEvent('download');await page.locator('#record').click();await(await download).saveAs(path.join(evidence,'cheering-cheer.webm'));report.recording='evidence/cheering-cheer.webm';
  await page.evaluate(()=>window.__v90.reset());await page.locator('[data-decision="hold"]').click();await page.locator('#notes').fill('자동 검수 예시: 적용 확인. 사용자 외형 검수 대기.');await page.evaluate(()=>window.__v90.selectExpression('thinking'));await page.evaluate(()=>window.__v90.selectExpression('cheering'));check((await getState()).decision==='hold','Per-expression decision lost');check(await page.locator('#notes').inputValue()==='자동 검수 예시: 적용 확인. 사용자 외형 검수 대기.','Per-expression note lost');
  const exported=page.waitForEvent('download');await page.locator('#export').click();await(await exported).saveAs(path.join(reports,'review-export-sample.json'));report.checks.perExpressionReviewExport=true;
  await page.reload();await page.waitForFunction(()=>window.__v90?.getState()?.ready);await page.evaluate(()=>window.__v90.selectExpression('cheering'));check((await getState()).decision==='hold','Review not persisted after reload');report.checks.reviewPersistence=true;
  await page.setViewportSize({width:390,height:844});await settle();check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow');await page.screenshot({path:path.join(evidence,'mobile.png'),fullPage:true});report.checks.mobileNoOverflow=true;
  await page.setViewportSize({width:1600,height:1100});await page.evaluate(async()=>{await window.__v90.selectExpression('thinking');window.__v90.reset();});await settle();await page.screenshot({path:path.join(evidence,'final-page.png'),fullPage:true});
 }
 check(!report.consoleErrors.length&&!report.pageErrors.length&&!report.failedRequests.length&&!report.badResponses.length,'Browser errors recorded');report.success=true;
}catch(error){report.error=String(error);console.error(error);await page.screenshot({path:path.join(evidence,'failure.png'),fullPage:true}).catch(()=>{});}finally{report.finishedAt=new Date().toISOString();await save(smoke?'smoke-validation.json':'browser-validation.json',report);await browser.close();}
console.log(JSON.stringify({success:report.success,error:report.error,loaded:report.loaded.length,errors:[report.consoleErrors.length,report.pageErrors.length,report.failedRequests.length,report.badResponses.length],checks:report.checks},null,2));if(!report.success)process.exitCode=1;
