import {COMBOS,COMBO_STEPS} from './combos.mjs';
import {createRuntime} from './runtime.mjs';import {createSequenceController} from './selection-policy.mjs';const sequence=createSequenceController();const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const desktop=location.pathname==='/desktop';document.body.classList.toggle('desktop',desktop);document.documentElement.classList.toggle('desktop',desktop);let runtime;let busy=0;let reviews={};try{reviews=JSON.parse(localStorage.getItem('doreumi-v98-reviews')||'{}');if(!reviews||Array.isArray(reviews)||typeof reviews!=='object')reviews={};}catch{}
const download=(blob,name)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
const key=()=>{const s=runtime.getState();return [s.expression,s.attachments.head?.id??'',s.attachments.hand?.id??'',s.sceneProp?.id??'',s.badge?.id??'',s.model.active,s.season,s.effect].join('|');};
function sync(){const s=runtime.getState();for(const o of $('#action').options){o.hidden=o.disabled=!s.candidateMode&&!runtime.manifest.actions.includes(o.value);}$('#expression').value=s.expression;$('#action').value=s.model.active;$('#head').value=s.attachments.head?.id??'';$('#hand').value=s.attachments.hand?.id??'';$('#scene-prop').value=s.sceneProp?.id??'';$('#badge').value=s.badge?.id??'';$('#scene-prop').disabled=$('#badge').disabled=!s.candidateMode||busy>0;$('#season').value=s.season;$('#effect').value=s.effect.startsWith('#')?'custom':s.effect;if(s.effect.startsWith('#'))$('#custom-color').value=s.effect;$('#candidates').checked=s.candidateMode;$('#head').disabled=$('#hand').disabled=!s.candidateMode||busy>0;$('#play').textContent=s.model.paused?'재생':'일시정지';$('#identity').textContent=JSON.stringify({표정:{이름:s.expressionAsset.label,버전:s.expressionAsset.version,승인:'V60 적용 사용자 통과',원본:s.expressionAsset.model},소품:s.attachments,배치소품:s.sceneProp,가슴배지:s.badge,나선색:s.effect,행동:s.actionAsset,V60:s.modelSha256},null,2);const review=reviews[key()];$('#notes').value=review?.note??'';$('#decision').textContent=review?.decision??'판정 전';}
async function run(fn){sequence.cancel();busy++;$('#head').disabled=$('#hand').disabled=$('#scene-prop').disabled=$('#badge').disabled=true;try{await fn();$('#notice').textContent='V60 적용 중 · 표정 승인 / 소품 후보 검수';}catch(e){$('#notice').textContent=e.message;}finally{busy--;sync();$('#winter-preset').disabled=$('#wand-preset').disabled=!runtime.getState().candidateMode;}}
function save(decision){reviews[key()]={decision:decision??reviews[key()]?.decision??'hold',note:$('#notes').value,at:new Date().toISOString()};localStorage.setItem('doreumi-v98-reviews',JSON.stringify(reviews));$('#decision').textContent=reviews[key()].decision;}
try{
 runtime=await createRuntime({canvas:$('#scene'),desktop,onState:s=>{$('#timeline').value=s.model.progress;}});window.__v98=runtime;
 for(const a of runtime.manifest.expressions)$('#expression').add(new Option(a.label+' · '+a.version,a.id));for(const id of runtime.viewer.clips.keys())$('#action').add(new Option(({MegaphoneSpeak:'확성기로 말하기',CarryBag:'주머니 들기'}[id]??id)+(runtime.manifest.actions.includes(id)?' · 승인':' · 후보'),id));for(const b of runtime.manifest.badges)$('#badge').add(new Option(b.label+' · 배지 후보',b.id));for(const p of runtime.manifest.props.filter(p=>p.slot))$(p.slot==='scene'?'#scene-prop':'#'+p.slot).add(new Option(p.label+' · 후보',p.id));
 $('#expression').onchange=e=>run(()=>runtime.selectExpression(e.target.value));$('#action').onchange=e=>run(()=>runtime.play(e.target.value));$('#candidates').onchange=e=>run(()=>runtime.setCandidateMode(e.target.checked));for(const slot of ['head','hand'])$('#'+slot).onchange=e=>run(()=>runtime.selectProp(slot,e.target.value));$('#scene-prop').onchange=e=>run(()=>runtime.selectProp('scene',e.target.value));$('#badge').onchange=e=>run(()=>runtime.selectBadge(e.target.value));$('#custom-color').oninput=e=>run(()=>runtime.setEffect(e.target.value==='custom'?$('#custom-color').value:e.target.value));$('#season').onchange=e=>run(()=>runtime.setSeason(e.target.value));$('#effect').onchange=e=>run(()=>runtime.setEffect(e.target.value));$$('[data-view]').forEach(b=>b.onclick=()=>runtime.setView(b.dataset.view));$('#zoom').oninput=e=>runtime.setZoom(Number(e.target.value)/100);$('#timeline').oninput=e=>run(()=>runtime.seek(Number(e.target.value)));$('#play').onclick=()=>run(()=>runtime.pause(!runtime.getState().model.paused));$('#reset').onclick=()=>run(()=>runtime.reset());
 $('#capture').onclick=async()=>download(await runtime.viewer.captureBlob(),'v98-combination.png');$('#record').onclick=()=>run(async()=>{const stream=$('#scene').captureStream(30),chunks=[],rec=new MediaRecorder(stream,{mimeType:'video/webm'});try{rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const stop=new Promise(r=>rec.onstop=r);rec.start();runtime.play(runtime.getState().model.active);await new Promise(r=>setTimeout(r,5000));rec.stop();await stop;download(new Blob(chunks,{type:'video/webm'}),'v98-motion.webm');}finally{stream.getTracks().forEach(t=>t.stop());}});
 for(const [button,prop,action]of [['megaphone-preset','megaphone','MegaphoneSpeak'],['bag-preset','christmas-gift-sack','CarryBag']])$('#'+button).onclick=()=>run(()=>sequence.run([()=>{runtime.reset();runtime.setCandidateMode(true);},()=>runtime.selectProp('hand',prop),()=>runtime.play(action)]));
 for(const preset of COMBOS){$('#combo').add(new Option(preset.label,preset.id));}$('#apply-combo').onclick=()=>run(()=>sequence.run(COMBO_STEPS(runtime,COMBOS.find(c=>c.id===$('#combo').value))));
 $('#winter-preset').disabled=$('#wand-preset').disabled=true;
 $('#winter-preset').onclick=()=>run(()=>sequence.run([()=>{if(!runtime.getState().candidateMode)throw new Error('후보 시험을 먼저 켜세요.');runtime.reset();},()=>runtime.selectExpression('greeting_smile'),()=>runtime.selectProp('head','santa-hat'),()=>{runtime.setSeason('winter');runtime.play('Wave');}]));$('#wand-preset').onclick=()=>run(()=>sequence.run([()=>{if(!runtime.getState().candidateMode)throw new Error('후보 시험을 먼저 켜세요.');runtime.reset();},()=>runtime.selectExpression('cheering'),()=>runtime.selectProp('hand','magic-wand'),()=>{runtime.setEffect('gold');runtime.play('Cheer');}]));
 $$('[data-decision]').forEach(b=>b.onclick=()=>save(b.dataset.decision));$('#notes').oninput=()=>save();$('#export').onclick=()=>download(new Blob([JSON.stringify({version:'V98',reviews,state:runtime.getState(),source:runtime.manifest},null,2)],{type:'application/json'}),'v98-review.json');$('#desktop-close').onclick=()=>window.doreumiDesktop?.close();window.doreumiDesktop?.ready({loaded:true,version:'V98',modelSha256:runtime.manifest.model.sha256});window.addEventListener('beforeunload',()=>runtime.dispose());sync();$('#notice').textContent='준비 완료 · 승인 표정 34종 / 후보 소품 시험은 직접 켜주세요.';
}catch(e){$('#notice').textContent='시작 실패: '+e.message;console.error(e);window.__v98={getState:()=>({ready:false,error:e.message})};window.doreumiDesktop?.ready({loaded:false});}
