import {uprightPlacement} from './upright.mjs';
import * as THREE from 'three';import {surfaceFrame} from './attachment-frame.mjs';import {createLatestSelection} from './selection-policy.mjs';
export function disposeProp(root){root?.traverse(o=>{if(!o.isMesh)return;o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture){v.dispose();v.image?.close?.();}m.dispose();}});}
function skinNormal(mesh,index){const g=mesh.geometry,base=new THREE.Vector3().fromBufferAttribute(g.attributes.normal,index).applyMatrix3(new THREE.Matrix3().setFromMatrix4(mesh.bindMatrix));const ids=new THREE.Vector4().fromBufferAttribute(g.attributes.skinIndex,index),weights=new THREE.Vector4().fromBufferAttribute(g.attributes.skinWeight,index),result=new THREE.Vector3();for(let k=0;k<4;k++){const weight=weights.getComponent(k);if(!weight)continue;const bone=ids.getComponent(k),matrix=new THREE.Matrix4().multiplyMatrices(mesh.skeleton.bones[bone].matrixWorld,mesh.skeleton.boneInverses[bone]);result.addScaledVector(base.clone().applyMatrix3(new THREE.Matrix3().setFromMatrix4(matrix)),weight);}return result.applyMatrix3(new THREE.Matrix3().setFromMatrix4(mesh.bindMatrixInverse)).applyMatrix3(new THREE.Matrix3().getNormalMatrix(mesh.matrixWorld)).normalize();}
export function createAttachments({scene,model,loader,configs,props}){
 const slots={head:null,hand:null},controllers={};let candidateMode=false,action='Idle';const mesh=[];model.traverse(o=>{if(o.isSkinnedMesh)mesh.push(o);});
 function clear(slot){controllers[slot]?.cancel();const s=slots[slot];if(s){scene.remove(s.group);disposeProp(s.root);}slots[slot]=null;}
 function update(){model.updateMatrixWorld(true);for(const s of Object.values(slots)){if(!s)continue;try{const points=s.config.triangle.map(i=>s.mesh.localToWorld(s.mesh.getVertexPosition(i,new THREE.Vector3()))),normal=s.config.triangle.reduce((v,i,k)=>v.addScaledVector(skinNormal(s.mesh,i),s.config.barycentric[k]),new THREE.Vector3()),frame=surfaceFrame(points,s.config.barycentric,normal);s.group.matrix.copy(frame).multiply(s.bindInverse).multiply(s.placement);s.group.matrixWorldNeedsUpdate=true;s.group.visible=true;s.error=null;s.contact=points.reduce((p,v,i)=>p.addScaledVector(v,s.config.barycentric[i]),new THREE.Vector3()).toArray();if(s.config.orientationMode==='upright')s.group.matrix.copy(uprightPlacement(new THREE.Vector3().fromArray(s.contact),s.config));}catch(e){s.group.visible=false;s.error=e.message;}}}
 for(const slot of Object.keys(slots))controllers[slot]=createLatestSelection({load:async id=>{const config=configs[id],prop=props.find(p=>p.id===id&&p.slot===slot);if(!candidateMode||!config||config.status==='blocked'||!prop)throw new Error('이 소품은 부착 검수 대상이 아닙니다.');if(!config.allowedActions.includes(action))throw new Error('현재 행동에서는 접촉 미검증: '+action);return {root:(await loader.loadAsync(prop.modelUrl)).scene,config,prop};},dispose:v=>disposeProp(v.root),apply:({root,config,prop})=>{
  if(!candidateMode||!config.allowedActions.includes(action))throw new Error('선택 조건이 변경되었습니다.');const target=mesh.find(m=>m.name===config.meshName);if(!target)throw new Error('V60 부착 표면 없음');
  const group=new THREE.Group();group.matrixAutoUpdate=false;group.add(root);const placement=new THREE.Matrix4().compose(new THREE.Vector3().fromArray(config.position),new THREE.Quaternion().setFromEuler(new THREE.Euler(...config.rotation)),new THREE.Vector3().setScalar(config.scale));placement.multiply(new THREE.Matrix4().makeTranslation(...config.propContact.map(v=>-v)));
  const old=slots[slot];if(old){scene.remove(old.group);disposeProp(old.root);}slots[slot]={root,group,mesh:target,config,prop,placement,bindInverse:new THREE.Matrix4().fromArray(config.bindFrame).invert()};scene.add(group);update();}});
 return {async select(slot,id){if(!controllers[slot])throw new Error('Unknown slot');if(!id){clear(slot);return;}return controllers[slot].select(id);},clear,update,setCandidateMode(v){candidateMode=!!v;if(!candidateMode)for(const slot of Object.keys(slots))clear(slot);},setAction(name){for(const s of Object.values(slots))if(s&&!s.config.allowedActions.includes(name))throw new Error(`${s.prop.label}: ${name} 조합은 접촉 미검증`);action=name;},getState(){return Object.fromEntries(Object.entries(slots).map(([slot,s])=>{if(!s)return [slot,null];const textures=[];s.root.traverse(o=>{if(o.isMesh)textures.push({width:o.material.map?.image?.width,height:o.material.map?.image?.height});});return [slot,{id:s.prop.id,visible:s.group.visible,error:s.error,contact:s.contact,contactError:s.contact?new THREE.Vector3().fromArray(s.config.propContact).applyMatrix4(s.group.matrix).distanceTo(new THREE.Vector3().fromArray(s.contact)):null,textures,model:s.prop.model,version:'V48',sourceApproval:'candidate',attachmentStatus:s.config.status,allowedActions:s.config.allowedActions}];}));},dispose(){for(const slot of Object.keys(slots)){clear(slot);controllers[slot].dispose();}}};
}
