import {createBadgeLoader} from './badge-loader.mjs';import {createBadgeAttachment} from './badge-attachment.mjs';
import {sceneActionAllowed} from './scene-placement.mjs';
import {resolveSpiralColor} from './spiral-colors.mjs';import {createSceneProps} from './scene-props.mjs';
import {createToolClips,TOOL_ACTIONS} from './tool-motion.mjs';
import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createPropLoader} from './prop-loader.mjs';
import {createImageGLTFLoader,loadImage} from './image-loader.mjs';
import {createV60Viewer,loadGlbFromUrl} from './viewer-core.mjs';import {createFaceMaterial} from '/v90/face-material.mjs';import {geometrySnapshot} from '/v88/transfer.mjs';import {createLatestSelection} from './selection-policy.mjs';import {createAttachments,disposeProp} from './attachments.mjs';import {createSeasonalEffects} from '/v87/seasonal-effects.mjs';import {createSpiralEffects} from './spiral-effects.mjs';
async function bytes(url){const r=await fetch(url);if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.arrayBuffer();}
export async function createRuntime({canvas,desktop=false,onState=()=>{}}){
 const manifest=await(await fetch('/api/manifest')).json(),configs=await(await fetch('/data/attachments.json')).json(),badgeConfig=await(await fetch('/data/badge-attachment.json')).json();let badgeAttachment,sceneProps,attachments,face,spiral,season,expressionController,disposed=false;const state={ready:false,expression:'neutral',candidateMode:false,effect:'navy',season:'none',error:null};
 const viewer=await createV60Viewer({canvas,desktop,onFrame:()=>{attachments?.update();badgeAttachment?.update();return state.ready&&!viewer.state.paused&&(state.effect!=='navy'||state.season!=='none');},onState:()=>{if(state.ready)onState(getState());}});viewer.seek(0);viewer.model.traverse(o=>{if(o.isMesh)o.receiveShadow=false;});
 viewer.model.updateMatrixWorld(true);viewer.floor.position.y=new THREE.Box3().setFromObject(viewer.model).min.y-.008;
 const originals=new Map();viewer.model.traverse(o=>{if(o.isMesh)originals.set(o,o.material);});const originalClips=[...viewer.clips.values()];const before=await geometrySnapshot(viewer.model,originalClips);for(const clip of createToolClips(viewer.clips.get('Idle'))){viewer.clips.set(clip.name,clip);viewer.actions.set(clip.name,viewer.mixer.clipAction(clip));}
 const loader=createImageGLTFLoader(),source=(await loadGlbFromUrl(loader,manifest.expressions.find(a=>a.id==='neutral').modelUrl)).scene;let sourceMaterial;source.traverse(o=>{if(o.isMesh&&o.material.map&&!sourceMaterial)sourceMaterial=o.material;});
 face=createFaceMaterial(viewer.model,source,manifest.geometry.regionsXY,manifest.expressions.find(a=>a.id==='neutral'));
 const [position,normal,mask]=await Promise.all(['neutral-position-delta','neutral-normal-delta','mask'].map(n=>bytes(n==='mask'?'/assets/v60-spiral-mask.bin':`/data/${n}.bin`).then(b=>new Float32Array(b))));
 viewer.model.traverse(o=>{if(!o.isMesh)return;if(position.length!==o.geometry.attributes.position.array.length)throw new Error('V60 morph count mismatch');o.geometry.morphTargetsRelative=true;o.geometry.morphAttributes.position=[new THREE.Float32BufferAttribute(position,3)];o.geometry.morphAttributes.normal=[new THREE.Float32BufferAttribute(normal,3)];o.updateMorphTargets();o.morphTargetInfluences[0]=1;o.material=face.material(originals.get(o));});
 attachments=createAttachments({scene:viewer.scene,model:viewer.model,loader:createPropLoader(),configs,props:manifest.props});badgeAttachment=createBadgeAttachment({scene:viewer.scene,model:viewer.model,loader:createBadgeLoader(new Set(manifest.badges.map(b=>b.id))),badges:manifest.badges,config:badgeConfig});sceneProps=createSceneProps({scene:viewer.scene,loader:createPropLoader(),props:manifest.props});season=await createSeasonalEffects(viewer.scene,{textureUrls:manifest.seasons});
 function effect(id){resolveSpiralColor(id);state.effect=id;if(id!=='navy'&&!spiral)spiral=createSpiralEffects(viewer.model,viewer.scene,{mask});if(spiral){spiral.setMood(id);spiral.setPaused(viewer.state.paused);}viewer.invalidate();return getState();}
 expressionController=createLatestSelection({load:async id=>{const asset=manifest.expressions.find(a=>a.id===id);if(!asset)throw new Error('승인 표정 없음');return {asset,image:await loadImage(asset.textureUrl)};},dispose:v=>{v.image.src='';},apply:({asset,image})=>{
  const oldMap=sourceMaterial.map,nextMap=new THREE.Texture(image);nextMap.flipY=false;nextMap.colorSpace=THREE.SRGBColorSpace;sourceMaterial.map=nextMap;let next;
  try{next=createFaceMaterial(viewer.model,source,manifest.geometry.regionsXY,asset);}catch(e){sourceMaterial.map=oldMap;nextMap.dispose();throw e;}
  spiral?.dispose();spiral=null;for(const [o,m]of originals){const old=o.material;o.material=next.material(m);old.dispose();}face.dispose();face=next;oldMap.dispose();oldMap.image?.close?.();state.expression=asset.id;effect(state.effect);state.error=null;
 }});
 function getState(){return {...state,version:'V98',modelSha256:manifest.model.sha256,expressionCount:34,actionAsset:{name:viewer.state.active,version:TOOL_ACTIONS[viewer.state.active]?'V98':'V60',approval:TOOL_ACTIONS[viewer.state.active]?'candidate':'user-approved',source:TOOL_ACTIONS[viewer.state.active]?'src/tool-motion.mjs':manifest.model.path},expressionAsset:manifest.expressions.find(a=>a.id===state.expression),attachments:attachments?.getState(),badge:badgeAttachment?.getState(),sceneProp:sceneProps?.getState(),model:viewer.state,material:face?.report,releaseComplete:false};}
 function pause(v){viewer.pause(v);spiral?.setPaused(v);season.setPaused(v);return getState();}
 function play(name){const placed=sceneProps?.getState();if(placed&&!sceneActionAllowed(placed.id,name))throw new Error('배치 소품과 이 행동의 접촉은 미검증입니다. 소품을 해제하세요.');if(TOOL_ACTIONS[name]&&(!state.candidateMode||attachments.getState().hand?.id!==TOOL_ACTIONS[name]))throw new Error('이 후보 동작에는 해당 도구 착용이 필요합니다.');if(!manifest.actions.includes(name)&&!state.candidateMode)throw new Error('미승인 행동: 후보 시험 모드를 켜세요.');attachments.setAction(name);viewer.play(name);pause(false);return getState();}
 function setCandidateMode(v){state.candidateMode=!!v;attachments.setCandidateMode(v);badgeAttachment.setCandidateMode(v);sceneProps.setCandidateMode(v);viewer.invalidate();if(!v&&!manifest.actions.includes(viewer.state.active))play('Idle');return getState();}
 function reset(){expressionController.cancel();attachments.clear('head');attachments.clear('hand');badgeAttachment.clear();sceneProps.clear();effect('navy');season.setSeason('none');state.season='none';play('Idle');viewer.seek(0);pause(true);viewer.setView('front');viewer.setZoom(1);return getState();}
 async function selectExpression(id){try{await expressionController.select(id);return getState();}catch(e){state.error=e.message;throw e;}}
 const runtime={manifest,viewer,configs,badgeConfig,THREE,loader,getState,selectExpression,selectBadge:async id=>{await badgeAttachment.select(id);await viewer.renderer.compileAsync(viewer.scene,viewer.camera);viewer.invalidate();viewer.renderer.render(viewer.scene,viewer.camera);return getState();},selectProp:async(slot,id)=>{if(id&&slot==='scene'&&!sceneActionAllowed(id,viewer.state.active))throw new Error('먼저 초기화하거나 해당 조합 버튼을 사용하세요.');if(id&&((slot==='scene'&&attachments.getState().hand)||(slot==='hand'&&sceneProps.getState())))throw new Error('손 도구와 배치 소품의 동시 조합은 아직 미검증입니다.');if(slot==='scene')await sceneProps.select(id);else await attachments.select(slot,id);await viewer.renderer.compileAsync(viewer.scene,viewer.camera);viewer.invalidate();viewer.renderer.render(viewer.scene,viewer.camera);return getState();},setCandidateMode,setSeason(id){season.setSeason(id);state.season=id;viewer.invalidate();return getState();},setEffect:effect,play,pause,seek(p){viewer.seek(p);pause(true);attachments.update();badgeAttachment.update();viewer.renderer.render(viewer.scene,viewer.camera);return getState();},setView:v=>viewer.setView(v),setZoom:z=>viewer.setZoom(z),reset,async invariants(){const after=await geometrySnapshot(viewer.model,originalClips);return {unchanged:before.hashes.every(h=>after.hashes.some(a=>a.label===h.label&&a.sha256===h.sha256)),before,after};},dispose(){if(disposed)return;disposed=true;expressionController.dispose();attachments.dispose();badgeAttachment.dispose();sceneProps.dispose();spiral?.dispose();season.dispose();face.dispose();disposeProp(source);for(const m of originals.values())m.dispose();viewer.dispose();}};
 state.ready=true;pause(true);return runtime;
}
